### ISSUE TITLE
ProxyMiddleware HTTP Basic Auth fails on base64.encodestring in Python 3

### ISSUE THREAD

**Issue by nirvana-msu** [fabienvauchelles/scrapoxy-python-api#1]
Hi,

First of all, thanks for a fantastic tool! I have a problem using it with Python 3 and HTTP Basic Auth, though. The problem is this line in `ProxyMiddleware`:

```py
self._proxy_auth = u'Basic ' + base64.encodestring(parts.group(2)[:-1]).strip() 
```

While the code works in Python 2, the `base64.encodestring` expects `bytes`, not `str`, in Python 3, thus failing (and it is also depreciated). Discussed in some detail on stackoverflow [here](http://stackoverflow.com/questions/31144988/base64-encodestring-failing-in-python-3).

**Comment by nirvana-msu** [comment]
There are more cases like this throughout the code, e.g. `self._password = base64.b64encode(password)` in `Commander` class. Is Python 3 not supported by this extension?

For the record, Scrapy [does work with Python 3.3+](https://doc.scrapy.org/en/latest/faq.html#what-python-versions-does-scrapy-support), so would be very nice if this extension did too..

**Comment by fabienvauchelles** [comment]
Hello @Alexgmin ,

Thanks for PR. 1.9 is release :)

Fabien.
