### ISSUE TITLE
JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by andrew-werdna** [fabienvauchelles/scrapoxy-python-api#5]
I have been using Scrapy/Scrapoxy for a while now with great success. Until I moved the entire setup onto an AWS EC2 instance itself (**so I'm running scrapy/scrapoxy _FROM_ an EC2 instance, as well as proxying to EC2 instances**

I think this **may** be due to the fact  that on the EC2 machine that is _hosting_ the scrapy/scrapyd/scrapoxy is using Python 3.5.* and my desktop machine was using Python 2.7.13

OR, it could be because I'm telling scrapyd to run multiple spiders and scrapoxy is already scaled to the maximum?

In any case, here is the stack trace I'm getting.

```
[scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScaleMiddleware.spider_opened of <scrapoxy.downloadmiddlewares.scale.ScaleMiddleware object at 0x7feb48fffcf8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/local/lib/python3.5/dist-packages/scrapoxy/downloadmiddlewares/scale.py", line 45, in spider_opened
    min_sc, required_sc, max_sc = self._commander.get_scaling()
  File "/usr/local/lib/python3.5/dist-packages/scrapoxy/commander.py", line 76, in get_scaling
    result = json.loads(r.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

All of my spiders except one are running just fine. But one just crashes with no errors or anything. Scrapyd just moves it from active job area to 'finished' job area. Any thoughts? I love what you've made, btw. Awesome idea!

**Comment by fabienvauchelles** [comment]
@andrew-werdna Thx :)

I'm not a python 3.5 specialist. What do you think to move the line:

```
result = json.loads(r.content)
```

to

```
result = json.loads(r.content.decode('utf-8'))
```

?

can you check that ?

Fabien

**Comment by andrew-werdna** [comment]
I will do so!! Thank you for your reply!!

**Comment by andrew-werdna** [comment]
Excellent suggestion sir! I have submitted a PR for your approval!

**Comment by fabienvauchelles** [comment]
closed in https://github.com/fabienvauchelles/scrapoxy-python-api/pull/4

**Comment by fabienvauchelles** [comment]
@andrew-werdna It is fixed and migrated to Python 3

**Comment by fedelopezm** [comment]
dont work for me

**Comment by CesarIberth** [comment]
I'm working in this google's example https://cloud.google.com/iot/docs/samples/end-to-end-sample over one raspberry pi and this solve the problem in "cloudiot_pub_sub_example_server.py" file. 

Thanks @fabienvauchelles

**Comment by harshv2013** [comment]
> @andrew-werdna Thx :)
> 
> I'm not a python 3.5 specialist. What do you think to move the line:
> 
> ```
> result = json.loads(r.content)
> ```
> to
> 
> ```
> result = json.loads(r.content.decode('utf-8'))
> ```
> ?
> 
> can you check that ?
> 
> Fabien

Thank You.
It helped me.

**Comment by tarek421995** [comment]
thank you it is helped @fabienvauchelles

**Comment by ybabel** [comment]
Help me too (python 3.5 on raspbian)
